language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gwfernandez/fibo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gwfernandez/fibo-test npm run test

after_success:
  - docker build -t gwfernandez/fibo-client ./client
  - docker build -t gwfernandez/fibo-worker ./worker
  - docker build -t gwfernandez/fibo-server ./server
  - docker build -t gwfernandez/fibo-nginx ./nginx 
  # login in docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push gwfernandez/fibo-client
  - docker push gwfernandez/fibo-worker
  - docker push gwfernandez/fibo-server
  - docker push gwfernandez/fibo-nginx
